### ISSUE TITLE
Fix unexpected edges

### ISSUE THREAD

**Issue by Peque** [Peque/sphinxcadquery#11]
Sometimes edges are displayed in cylinders. See the [Bulebule mounting design](https://bulebule.readthedocs.io/en/latest/building.html#mounting).

The little holes have vertical edges (i.e.: the hole is not a smooth surface).

![Screenshot from 2019-09-29 21-29-17](https://user-images.githubusercontent.com/526577/65838127-39c18600-e300-11e9-9769-2d50ac3078a0.png)

Currently we are avoiding edges when the degrees between 2 surfaces is higher than 5 with:

```javascript
var edges = new THREE.EdgesGeometry( geometry, 5 );
```

But that sounds arbitrary.

- Is there a way to avoid edges in cylinders, which are supposed to be smooth surfaces independently of their diameter?
- Is it something we cannot fix and the only workaround is to increase the edges-degrees above 5 or increase the precision in the generated TJS file?
- Would using another intermediate format help?

**Comment by izhuravlev** [comment]
Hey @Peque,
I will be happy to have a look an try to figure out the solution as soon as I can!

**Comment by Peque** [comment]
@izhuravlev Great! :muscle:

You can also have a look at #10. Another issue related to edges display.

If you have any questions just ask. :wink:

**Comment by izhuravlev** [comment]
Hi @Peque,
I am looking forward to work on this bug during this weekend - already cloned the project and set up my environment - could you please tell me how can I test my work - for example, provide me with a testing file or explain how to create one? 
It will be awesome if you can also share with me some more details on how can I proceed with this one.
Thank You!

**Comment by Peque** [comment]
@izhuravlev Sure, you can use [this one](https://github.com/Bulebots/bulebule/blob/master/3d/mount.py) (it is actually the one on the picture).

Apart from that, and what is already written in this issue, I cannot give you further advise. :blush:

**Comment by izhuravlev** [comment]
Thank you @Peque, I will continue working on this one.

**Comment by Peque** [comment]
This should be fixed now by 6e9c73a56a5093869a04eab12b47edf739ba5de7.
