### ISSUE TITLE
extension doesn't work if html_context["css_files"] is modified.

### ISSUE THREAD

**Issue by rowanG077** [Peque/sphinxcadquery#19]
After a few hours of hair pulling debugging I found that this extension does not work if `html_context["css_files"]` in `conf.py` is set at all. The 3d view is not visible and it seems some click event on the page get swallowed.

So in `conf.py` the following works:

```
html_context = {
    # 'css_files': [ ]
}
``` 

But the following does not work:

```
html_context = {
    'css_files': [ ]
}
```

For some reason the `<link rel="stylesheet" href="_static/sphinxcadquerystatic/main.css" type="text/css">` is not included in the header in the broken version.

**Comment by rowanG077** [comment]
If I use `html_css_files` to add my own css it works.

**Comment by Peque** [comment]
@rowanG077 Thanks for reporting!

Should it work with `html_context["css_files"]` too? What is the preferred way with the latest Sphinx version?

If this should be supported with the latest version of Sphinx and is preferred over `html_css_files`, leave this open and/or feel free to contribute a fix! :stuck_out_tongue_winking_eye:

**Comment by rowanG077** [comment]
Using the `html_context` like that is undefined behaviour. I didn't know this. See https://github.com/sphinx-doc/sphinx/issues/2442
