### ISSUE TITLE
Request for license

### ISSUE THREAD

**Issue by shimwell** [Peque/sphinxcadquery#23]
Wondering if it might be possible to add a license file to the repository

I guess there is quite a lot to chose from these days, I wonder if it might be worth opting for the same one as CQ https://github.com/CadQuery/cadquery/blob/master/LICENSE

**Comment by Peque** [comment]
Yeah, good idea! :joy: 

BSD 3-clause should be fine. :blush:  

As in: https://raw.githubusercontent.com/markdownreveal/markdownreveal/master/LICENSE

Instead of "The Markdownreveal contributors", "The sphinxcadquery contributors".

**Comment by shimwell** [comment]
Super I can make that PR for your consideration

**Comment by Peque** [comment]
Closed by https://github.com/Peque/sphinxcadquery/pull/24.
