### ISSUE TITLE
increased visibility for package / relocation

### ISSUE THREAD

**Issue by shimwell** [Peque/sphinxcadquery#33]
Hi all

I've just been chatting with @Peque on LinkedIn and the idea of relocating this package to a new GitHub organization came up.

I think it might have been my recent splurge of messy PRs that triggered @Peque to think about moving it :blush: 

So we were wondering if the :star: CadQuery organization :star:  might be the best place to adopt this rather fantastic repo.

This would be helpful for the community of CadQuery users like myself who only came across this package by working :eyes: through the CadQuery source code. I think a relocation it will help the community find it and build nice docs pages :book:.

I have recently started using SphinxCadQuery [on a read the docs page](https://paramak--836.org.readthedocs.build/en/836/example_parametric_reactors.html) and am having great fun adding additional little features to this package. I am really happy that I've found something that I can actually pitch in and help with.

@Peque perhaps it would be good to pitch in on this issue just to be sure I've not misunderstood.

**Comment by Peque** [comment]
Yeah, that is correct. Once people start using and, specially, contributing to a package I think it is a good idea to move it into an organization.

[CadQuery's organization](https://github.com/CadQuery) seems like the perfect place for SphinxCadQuery so, if they are willing to accept the package under their umbrella, I'd be more than happy to transfer it! :blush:

I would volunteer as an administrator of the repository to handle issues/pull-requests if they want to.

**Comment by shimwell** [comment]
Thanks for that

What you you all think @adam-urbanczyk @dcowden @fragmuffin @jmwright @justbuchanan @marcus7070 @zignig would you be keen to accept a transfer?

**Comment by dcowden** [comment]
+1 from me, keeping everything in one place seems like a good idea to me!

**Comment by jmwright** [comment]
+1 Thanks for all the work you've done on this @Peque 

I think we would definitely still want you to be the primary admin for this repo. We can figure out the access rights within the GitHub org to make that happen.

**Comment by Peque** [comment]
@dcowden @jmwright Great! :blush: 

I think I just need permission to create repositories in the target organization in order to transfer it. Tell me when I am allowed and I will happily do the transfer.

**Comment by jmwright** [comment]
@Peque You should receive an invitation to the org at the member level. That should give you the access you need. After you add the repo I should be able to give you full access to administrate it.

**Comment by Peque** [comment]
@jmwright Thanks!

According to [GitHub docs](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository):

> The target account must not have a repository with the same name, or a fork in the same network

It seems [you already have a fork](https://github.com/CadQuery/sphinxcadquery) in the organization. So I guess that one would need to be deleted.

There is one star/watcher, so in case they want to be kept updated, @pphuth, I hope you read this! (you can star/watch this repository before or after the transfer to the organization) :smile:

**Comment by jmwright** [comment]
@Peque That repo has been deleted. It was 5 commits behind and 0 commits ahead, so I felt it was safe to delete it.

**Comment by Peque** [comment]
Done, thanks to everybody! :tada: 

The repository is now in a better place. :smile:

**Comment by jmwright** [comment]
@Peque I've given you admin access to that repo so you should be able to do everything you could before. Please let me know if you have any issues.
