### ISSUE TITLE
Error with upcaseTokens in pyparsing

### ISSUE THREAD

**Issue by shimwell** [Peque/sphinxcadquery#35]
I am just seeing a few errors using SphinxCadQuery in ReadTheDocs.

I notice a new version of PyParsing was [recently released on January the 21st](https://pypi.org/project/pyparsing/#history)

I'm wondering if it is related to changes in the PyParsing API 
https://github.com/pyparsing/pyparsing/blob/938f59d183ca790e41a1d995aa3d3e995df2fb19/CHANGES#L669-L670 

The error is .... and the full error can be seen [here](https://readthedocs.org/projects/paramak/builds/15863070/)
```bash
Could not import extension sphinxcadquery.sphinxcadquery (exception: cannot import name 'upcaseTokens' from 'pyparsing' (/home/docs/checkouts/readthedocs.org/user_builds/paramak/conda/156/lib/python3.8/site-packages/pyparsing/__init__.py))
```

I can look into this issue and try a PR

**Comment by Peque** [comment]
@shimwell Thanks for reporting this issue!

PyParsing is not a dependency of SphinxCadQuery, so maybe this is unrelated to SphinxCadQuery?

Anyway, if you find out more about this issue and/or want to contribute a PR, that would be very welcome! :blush:

**Comment by shimwell** [comment]
I did a little digging and you are right this error is not caused by sphinxcadquery. I guess error message just mislead me a bit

Moving the readthedocs build from caquery 2.1 to cadquery master version fixed the issue.

So seeing as this is not a sphinxcadquery issue and I've found a work around I will close this issue now. Sorry for the false alarm

**Comment by Peque** [comment]
@shimwell No problem, and thanks for the reporting! :blush:
